package cli

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/tacogips/ign/internal/app"
)

var rewindCmd = &cobra.Command{
	Use:   "rewind [output-path]",
	Short: "Remove files previously created by ign",
	Long: `Remove files previously created by ign and delete the local .ign state.

This command is the reverse of project generation:
1. Reads .ign/ign-files.json when available
2. Removes files that ign created
3. Cleans up empty directories
4. Deletes the .ign directory

If the manifest does not exist yet, ign falls back to the currently checked-out
template and variables to infer which files belong to ign.`,
	Args: cobra.MaximumNArgs(1),
	RunE: runRewind,
}

func runRewind(cmd *cobra.Command, args []string) error {
	outputPath := "."
	if len(args) > 0 {
		outputPath = args[0]
	}

	printInfo("Removing files generated by ign...")
	result, err := app.Rewind(cmd.Context(), app.RewindOptions{
		OutputDir:   outputPath,
		GitHubToken: getGitHubToken(""),
	})

	if result != nil {
		printInfo("")
		printInfo("Summary:")
		printInfo(fmt.Sprintf("  Removed: %d files", result.FilesRemoved))
		if result.FilesMissing > 0 {
			printInfo(fmt.Sprintf("  Missing: %d files (already absent)", result.FilesMissing))
		}
		if result.DirectoriesRemoved > 0 {
			printInfo(fmt.Sprintf("  Cleaned: %d empty directories", result.DirectoriesRemoved))
		}
		if len(result.Errors) > 0 {
			printWarning(fmt.Sprintf("%d errors occurred during rewind:", len(result.Errors)))
			for _, e := range result.Errors {
				printWarning(fmt.Sprintf("  - %v", e))
			}
		}
	}

	if err != nil {
		printErrorMsg(fmt.Sprintf("Rewind failed: %v", err))
		return err
	}

	printSuccess("ign-managed files removed")
	return nil
}
